agent:
  name: RLAgent
  args:
    model: ""
    api_base: ""
    temperature: 0.0
    max_new_tokens: 4096


task:
  class: Multi_ScreenshotMobileTask_AutoTest_v4_android_world
  args:
    save_dir: "./logs/android_lab-test"
    max_rounds: 50
    request_interval: 3
    picture_round: 2
    with_xml: true
    system_prompt: AW_SYSTEM_PROMPT_THINKING
    is_relative_bbox: true

eval:
  avd_name: Pixel_7_Pro_API_33
  docker_image_name: anonymous0bvcow8qfggoyac/mobilerl-androidlab-eval
  docker_args:
    port: 6060
  adb_path: /path/to/adb
  show_avd: false
  version: "v4"

judge: # if you want to eval android lab, you should set judge_model and api_key as https://github.com/THUDM/Android-Lab
  judge_model: "glm4"
  api_key: ""
  