from verl import DataProto

from verl.single_controller.ray import RayWorkerGroup


class AbstractWorker:
    world_size: int

    def init_model(self): ...
    def load_checkpoint(self, path, del_local_after_load=None): ...
    def save_checkpoint(self, path, hdfs_path=None, global_step=0, max_ckpt_to_keep=None): ...
    def model_to_gpu(self): ...
    def model_to_cpu(self): ...
    def optimizer_to_gpu(self): ...
    def optimizer_to_cpu(self): ...


class AbstractActorWorker(AbstractWorker):
    def update_actor(self, data: DataProto, offload=True): ...
    def sync_params(self): ...

class ActorWorkerGroup(AbstractActorWorker, RayWorkerGroup): ...

class AbstractRolloutWorker(AbstractWorker):
    def generate_sequences(self, data: DataProto): ...
    def sync_params(self, *args, **kwargs): ...
    def start_async_rollout_workers(self, size: int, queue, output_buffer): ...

class RolloutWorkerGroup(AbstractRolloutWorker, RayWorkerGroup): ...

class AbstractRefWorker(AbstractWorker):
    def compute_ref_log_prob(self, data: DataProto): ...

class RefWorkerGroup(AbstractRefWorker, RayWorkerGroup):...

class AbstractCriticWorker(AbstractWorker):
    def compute_values(self, data: DataProto, offload=True): ...
    def update_critic(self, data: DataProto):...

class CriticWorkerGroup(AbstractCriticWorker, RayWorkerGroup): ...
